//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : Account.java
//  @ Date : 2018/6/22
//  @ Author : 
//
//




public class Account {
	private static long account_id_cnt = 0;
	private long acount_id = 0;
	private String name;
	private String person_id;
	private String password;
	private double balance;
	private String create_time;
	private String create_code;
	public void Account(String name, String id, String pw, String code) {
	
	}
	
	public double getBalance() {
	
	}
	
	public long getAccountId() {
	
	}
	
	public String getPersonId() {
	
	}
	
	public boolean depositMoney(double money) {
	
	}
	
	public boolean drawMoney(double money) {
	
	}
}
