//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : AccountSet.java
//  @ Date : 2018/6/22
//  @ Author : 
//
//




public class AccountSet {
	public ArrayList account_set;
	public Account getAccountByPersonId(String person_id) {
	
	}
	
	public Account getAccountByAccountId(long account_id) {
	
	}
	
	public boolean delAccountByPersonId(String person_id) {
	
	}
	
	public boolean delAccountByAccountId(long account_id) {
	
	}
	
	public void ConnectAccount() {
	
	}
}
