//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : CreditCard.java
//  @ Date : 2018/6/22
//  @ Author : 
//
//




public class CreditCard extends Account {
	private String type = "Normal";
	public void CreditCard(String name, String id, String pw, String code) {
	
	}
	
	public void setVIP(int i) {
	
	}
}
