//
//
//  Generated by StarUML(tm) Java Add-In
//
//  @ Project : Untitled
//  @ File Name : DebaitCard.java
//  @ Date : 2018/6/22
//  @ Author : 
//
//




public class DebaitCard extends Account {
	public void DebaitCard(String name, String id, String pw, String code) {
	
	}
}
