@startuml

control main
control InputHandler
control Request
control Scheduler
control Elevator
collections OutputHandler

main --> InputHandler : Get the input
InputHandler --> Request : deal input and get
InputHandler -->Scheduler : pass the req list
Scheduler <--> Elevator : deal reqeust & move the elevator
Scheduler --> OutputHandler : output the request result
@enduml